
export enum Role {
    ADMIN_STORE = "ADMIN_STORE",
    PRODUCT_MANAGER = "PRODUCT_MANAGER",
    ACCOUNTING_MANAGER = "ACCOUNTING_MANAGER",
    MARKETING_MANAGER = "MARKETING_MANAGER",
    LANDINGPAGE_MANAGER = "LANDINGPAGE_MANAGER",
    SYSTEM_MANAGER = "SYSTEM_MANAGER",
    USER = "USER",
    ADMIN_GLOBAL = "ADMIN_GLOBAL",
}