import "@/styles/globals.css";
import type { Metadata, Viewport } from "next";
import { Inter } from "next/font/google";
import clsx from "clsx";
import { fontSans } from "@/config/fonts";
import { Providers } from "./providesr";
import NextAuthWrapper from "@/library/next.auth.wrapper";
import { ShoppingCartProvider } from "./context/ShoppingCartContext";
import { auth } from "@/auth";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Trang chủ",
  description: "Generated by Quân Nguyễn",
};
export const viewport: Viewport = {
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "white" },
    { media: "(prefers-color-scheme: dark)", color: "black" },
  ],
};
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang="en">
      <body
        className={clsx(
          "min-h-screen bg-background font-sans antialiased bg-gradient-to-br from-gray-100 to-gray-300 dark:bg-gradient-to-tl dark:from-gray-100 dark:to-gray-900",
          fontSans.variable,
        )}
      >
        <NextAuthWrapper session={session}>
          <Providers themeProps={{ attribute: "class", defaultTheme: "dark" }} >
            <ShoppingCartProvider>
              {children}
            </ShoppingCartProvider>
          </Providers>
        </NextAuthWrapper>
      </body>
    </html>
  );
}

